### ISSUE TITLE
Prepare a GATK-MT repository for the publication

### ISSUE THREAD

**Issue by HadleyKing** [UCI-GREGoR/mitochondria_m2_wdl#3]
- [x] UCI-GREGoR/mitochondria_m2_wdl#2
    - [ ] Document issues and suggestions
- [x] UCI-GREGoR/mitochondria_m2_wdl#4
- [x] UCI-GREGoR/mitochondria_m2_wdl#5

**Comment by HadleyKing** [comment]
no longer needed.
